### ISSUE TITLE
awkward-array API

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pylhe#21]
would be nice to be able to read this with awkward-array. Perhaps using some of the "behavioral interfaces"  we've been discussing with @jpivarski

**Comment by jpivarski** [comment]
As I understand it, LHE is a text format and pylhe parses it in Python. The fact that the source is text puts an upper limit on how fast it can be read, so we can choose convenience over speed when converting it to Awkward Array.

In the [Awkward 1 library](https://github.com/scikit-hep/awkward-1.0), you can find a function named [ak.from_iter](https://awkward-array.readthedocs.io/en/latest/_auto/ak.from_iter.html). Pass this an iterable of pure Python objects and it should convert to Awkward Arrays for analysis.

I'm realizing now that I might not have tested this function for arbitrary iterables (such as a Python generator). If it doesn't work, I'd like to know about it. Thanks!

**Comment by lukasheinrich** [comment]
do the python objects have to satisfy some API?

**Comment by jpivarski** [comment]
I haven't written down a specification, but that's a good idea.

As far as what it does (as-built), it _will_ take any Python iterable because the outermost loop is performed in a simple Python for loop:

https://github.com/scikit-hep/awkward-1.0/blob/367f2261350a04c7cbc96aac74f82f2c7487d47f/src/awkward1/operations/convert.py#L311-L312

Inside that, it's C++, recursively calling `builder_fromiter`:

https://github.com/scikit-hep/awkward-1.0/blob/367f2261350a04c7cbc96aac74f82f2c7487d47f/src/python/content.cpp#L698-L773

which takes

   * `None` to missing values ([ak.types.OptionType](https://awkward-array.readthedocs.io/en/latest/ak.types.OptionType.html) via [IndexedOptionArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.IndexedOptionArray.html))
   * `bool` (including NumPy `bool_`) to 8-bit boolean arrays
   * `int` (including NumPy integers) to 64-bit integer arrays (on both 32-bit and 64-bit systems)
   * `float` (including NumPy's floating types) to 64-bit float arrays
   * `bytes` (Python 2's `str`) to lists with [ak.behaviors.string.ByteStringBehavior](https://awkward-array.readthedocs.io/en/latest/_auto/ak.behaviors.string.ByteStringBehavior.html)
   * `str` (Python 2's `unicode`) to lists with [ak.behaviors.string.StringBehavior](https://awkward-array.readthedocs.io/en/latest/_auto/ak.behaviors.string.StringBehavior.html)
   * `tuple` to [ak.layout.RecordArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.RecordArray.html) with no field names: the tuples are assumed to all have the same length and the same type in each slot. If this is not true, the data type generalizes to a [ak.types.UnionType](https://awkward-array.readthedocs.io/en/latest/ak.types.UnionType.html).
   * `dict` (with string-valued keys) to [ak.layout.RecordArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.RecordArray.html) with field names: the dicts are assumed to have the same fields and the same type in each named field. If this is not true, the data type generalizes to a [ak.types.UnionType](https://awkward-array.readthedocs.io/en/latest/ak.types.UnionType.html).
   * `iterable` to [ak.layout.ListOffsetArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.ListOffsetArray.html), which are variable-length lists
   * NumPy `ndarray` also goes to [ak.layout.ListOffsetArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.ListOffsetArray.html). The `ak.from_iter` function cannot generate regular-length lists (because it never knows if the next list is going to have a different length; to make something with [ak.types.RegularType](https://awkward-array.readthedocs.io/en/latest/ak.types.RegularType.html), we'd need to use a different function.
   * mixtures of different types at the same level are given [ak.types.UnionType](https://awkward-array.readthedocs.io/en/latest/ak.types.UnionType.html) using [ak.layout.UnionArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.UnionArray.html). You want to try to keep that at a minimum because union types are limited: they can't be accessed in Numba, for instance. (Numba generates specialized code with no support for dynamic typing.)

I haven't addressed complex numbers (anywhere in Awkward), though that would perhaps be a good idea. Something to do universally, in a coherent sweep, though.

**Comment by lukasheinrich** [comment]
```
events = ak.from_iter({
  'particles': [
      {k:getattr(p,k) for k in pylhe.LHEParticle.fieldnames} for p in e.particles
  ],
  'eventinfo':  {k:getattr(e.eventinfo,k) for k in pylhe.LHEEventInfo.fieldnames}
  }
  
  for e in pylhe.readLHEWithAttributes(skhep_testdata.data_path('pylhe-testfile-pr29.lhe'))
)
```

this provides a basic interface
