### ISSUE TITLE
Reconsider tex2pix dependency

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pylhe#53]
`tex2pix` is a [core dependency of `pylhe`](https://github.com/scikit-hep/pylhe/blob/d9ce20436161ec174bde6555c7dd6e68f7f5e0ea/setup.cfg#L40-L43) but the [last release of `v0.3.1` was in 2016](https://pypi.org/project/tex2pix/0.3.1/#history), so it seems to be safely "unmaintained" at this point. The source code also doesn't seem to be publicly available on GitHub.

:wave: @agbuckley, as the author of `tex2pix` (thanks! :bow:), can you comment on if there is any plans to maintain `tex2pix` in the future? Or would you recommend that we look for an alternative that is more probable to be patched if there are issues that are found. I can imagine that you already have more than enough on your plate and being responsible for maintaining another codebase might very understandably not be high on the list. :)

**Comment by eduardo-rodrigues** [comment]
@matthewfeickert, allow me to chime in, since I use alternatives to get PDF/PNG/... files (if needed) in `DecayLanguage`: why not simply go for https://pypi.org/project/graphviz/ for dot files, which provide you with everything you need? To be honest I started by using `pydot` (still in use in `DecayLanguage`) but this is also seems unmaintained whereas `graphviz` is equivalent and very well maintained, hence I'm going to make the switch asap.

**Comment by agbuckley** [comment]
Hi all,

I'm coming in cold on this. There hasn't been a new tex2pix release because I'm not aware of problems with it -- if there are, let me know! I will be keeping it working because pyslha uses it for spectrum plotting. But note that it was written mainly for pyslha and there are probably nicer ways to do what it does -- I just factored it off because it seemed useful.
As you noted, I'm pretty busy, so it's a backburner project like many of my TeX-related ones, especially during Covid when time is tighter than ever. This and several other projects were hosted on Bitbucket, but then they deleted their Mercurial support and I've not got round to converting the repos to git and pushing to GitLab yet... I'll put it on my todo list.
Andy

**Comment by matthewfeickert** [comment]
> Hi all, I'm coming in cold on this.

Thanks. I didn't mean to drop you in without context, but I figured your insights would be useful here (they are).

> There hasn't been a new `tex2pix` release because I'm not aware of problems with it -- if there are, let me know!

Nope! Just wasn't sure what the state of things was if things did come up and where we would be able to open issues.

> But note that it was written mainly for pyslha and there are probably nicer ways to do what it does -- I just factored it off because it seemed useful. 

Nice. I didn't know about [PySLHA](http://www.insectnation.org/projects/pyslha) before (cc @kratsg in the event he doesn't either and would find it useful). At this point I'm just more interested in exploring options, and Eduardo has already given an example of another to try out as well.

> This and several other projects were hosted on Bitbucket, but then they deleted their Mercurial support and I've not got round to converting the repos to git and pushing to GitLab yet... I'll put it on my todo list.

Thanks! It would be cool to have them available, so we'll be on the lookout in the future.

**Comment by lukasheinrich** [comment]
@agbuckley does that mean we finally get to enjoy alll your projects on github/gitlab?

**Comment by agbuckley** [comment]
Heh, yes it's looking that way. Or all the ones I can remember/find, at least :-) It'd certainly make sense for the TeX ones to make their way on there, since my capacity these days is more on the "accepting merge requests" scale than being first mover!

Anyway, for now: https://gitlab.com/agbuckley/tex2pix

**Comment by matthewfeickert** [comment]
Thanks for making these public @agbuckley! I think this is great. :D
